### PR TITLE
Feature/fetch content

### PR DESCRIPTION
**Pull request by Leon0402**
Hi Roland, 

I made a first attempt to make using sqlpp17 easy with cmake, similar to what I did with sqlpp11. It's work in progess as I have only tested it with the sqlite3 lib and also only with fetchContent. 

There are a few things, which might be worth a discussion: 

### Version
For now I have added C++17 as required. I'm not quite sure if that's actually good practise, I kinda remember that you should not do it. Maybe it's because you cannot use it now with C++20, which would be bad (but I have to do some research on this) 

### Structure
I'm not quite sure if I like the overall structure of the repository. At first, it seemed reasonable to me to have each connector in it's on own subdirectory, but that might not be ideal. Imo this could lead to inconsistencies (especially regarding the cmake code). 

Proposal: Use subdirectories in each folder for each connector. So rather than connectors/sqlite3/include use include/sqlite3/   or something similar. And instead of connectors/sqlite3/tests use tests/sqlite3/. 

As I said, I see the main advantage of this in consistent cmake code. For instance, it's good practise to include tests like 
```
if(CMAKE_PROJECT_NAME STREQUAL PROJECT_NAME AND BUILD_TESTING)
  add_subdirectory(tests)
endif()
```
So tests are not built if the project is included in a subproject. With the current structure, this check has to be repeated in all connectors, instead of having it once. 
So in general all connectors seems cmake wise like their own project and therefore the code might look very different across them (like in one lib the targets are defined at the top, in the other at the bottom ...). 

### Building the connectors 

Currently all connectors are just built by default when all requirements are found. Especially when used with fetchContent (where the lib is basically copied to the project and built there) this might be not desirable as it increased build time. 

Instead I would define options for each Lib 
`option(BUILD_SQLITE3_CONNECTOR)`

One question would be though, if these should all default to true or all default to false. If the default is false that might be nicer for the consumer, but probably more difficult for you / the developers. 

Let me know what you think :) 

If you need some time to answer that's fine, I'm not sure how much time I have either and will work on this when I have some time.

### CODE REVIEW

**Comment by rbock** [comment]
Hi Leon,

> I made a first attempt to make using sqlpp17 easy with cmake, similar to what I did with sqlpp11. It's work in progess as I have only tested it with the sqlite3 lib and also only with fetchContent.

Cool :-)

> There are a few things, which might be worth a discussion:
> ### Version
> 
> For now I have added C++17 as required. I'm not quite sure if that's actually good practise, I kinda remember that you should not do it. Maybe it's because you cannot use it now with C++20, which would be bad (but I have to do some research on this)

Personally, I would not worry about it too much right now, as the library is not fit for production anyway.
But long term, yes, it should be possible for users to specify C++20, if they wanted.

> ### Structure
> Proposal: Use subdirectories in each folder for each connector. So rather than connectors/sqlite3/include use include/sqlite3/ or something similar. And instead of connectors/sqlite3/tests use tests/sqlite3/.

Sound good to me. Feels more natural.

> ### Building the connectors
> One question would be though, if these should all default to true or all default to false. If the default is false that might be nicer for the consumer, but probably more difficult for you / the developers.

Yes, false would be nicer, I think. Especially since more connectors might get added over time.

> Let me know what you think :)

 Thanks for looking at this from the build perspective!

I consider this library an important step towards the "final" reflection-based version. You proposed changes will make future development  smoother for sure.

Best,

Roland

**Comment by Leon0402** [comment]
Hi Roland, 

I made the proposed changes. There are two noticeable things that I changed that might need discussion: 

- I put everything pure sqlpp17 in a folder named core as it seemed better to me to have all connector next to sqlpp17 rather than inside (where all other folders of slp17 would be and you wouldn't find anything). The only drawback is that the include path changed to <sqlpp17/core/...> for the lib (still <sqlpp17/connector/...> for the connectors). Which I personally actually like, but you should decide, if that's acceptable. On result of this is that my PR is now changing 345 files (because I had to fix all the includes), sorry for that 
- I made a target for sqlcipher. I figured you might want to be able to install all connectors on your system (with sqlite3 **and** sclcipher). Furthermore it's easier to use (just set one variable instead of two) and more natural to read in the consumer project (-> link to sqlpp17::sqlcipher rather than slpp17::sqlite3 if you use sqlcipher)

The test currently don't build, so I commented them out. But it seems like they don't build on developer branch either, so this is probably something for another PR. 
Also the sqlcipher example doesn't run, there are some error messages: 
image
I assume I didn't break that either, so again something for another PR?

**Comment by rbock** [comment]
Hi Leon,

Thanks for you patience. I like the structure. Let's do it. 

Best,

Roland

**Comment by rbock** [comment]
Note: It will take some time for me to look at the build problems.

**Pull request merged**
