### PR TITLE
Feature/tests

### PR DESCRIPTION
**Pull request by Leon0402**
I've added the Catch2 Testing Framework as discussed as well as some documentation on how to build and run the tests. 

For now I put the new test in a new subdirectory until old tests are migrated. 

I'm not yet sure how to build up the test suite. Usually I use a class / file based testing. 

So starting off with `avg.h` I would say `check_avg_args` is an implementation detail and should not be tested explicitly (private function in an OOP world). 
Therefore I would check if `avg` returns the correct case for all valid and invalid expressions. So 4 cases for both overloadings. 

I also think that checking the sql serialization makes sense to put in here for `avg` as well, altough it's technically handled as part of the `aggregate_t` part. 

(Btw. my naming skills for the BTD tests are probably improveable, I tried my best, but I sometimes have a hard time not writing in "then it should work", but be a little bit more specific)

I also like the approach you had before of seperating the test more in terms of features, so say "serializing". I just fear it might then be easier to forget test cases that way. 

Let me know what you think. You know the library the best and are in a much better position to come up with testing strategies. 

I actually don't know C++ well enough to understand the code fully (too much template and auto), but I plan on leveling my skills a little bit up while writing the test :-)

### CODE REVIEW

**Comment by rbock** [comment]
Hi Leon,

Thanks for the PR. And sorry for taking so long to reply. I was super busy with something else.

Regarding `check_avg_args`: This is similar to a concept in c++20. It would definitely make sense to test it. These would be compile time tests, though.

The serialization tests are definitely useful. The current code is readable. The only challenge I see is the extreme verbosity. The WHEN/THEN setup seems rather artificial.

I am by no means a catch2 expert. But can we write something like

```C++
SCENARIO("Serializing avg sql statement")
{
      REQUIRE(to_sql_string_c(::sqlpp::context_base{}, avg(tabPerson.id) == "AVG(tab_person.id)");  
      REQUIRE(to_sql_string_c(::sqlpp::context_base{}, avg(::sqlpp::distinct, tabPerson.id) == "AVG(DISTINCT tab_person.id)");
}
```

Thanks,

Roland

**Comment by Leon0402** [comment]
There is another syntax, which is less verbose: 

```
TEST_CASE( "Serializing avg sql statement" ) {
    SECTION( "average statement is converted to string" ) {
        // Act 
        std::string avgString = to_sql_string_c(::sqlpp::context_base{}, avg(tabPerson.id));
        
        // Assert
        REQUIRE(avgString == "AVG(tab_person.id)");
    }
    SECTION( "resizing smaller changes size but not capacity" ) {
        // Act
        std::string avgString = to_sql_string_c(::sqlpp::context_base{}, avg(::sqlpp::distinct, tabPerson.id));

        // Assert
        REQUIRE(avgString == "AVG(DISTINCT tab_person.id)");
    }
}
 ```
 
 So: WHEN = Section   and there is no THEN
 
 You can write the inner part of SECTION the way you did it. Personally I believe though that the verbosity here is good. It follows the "arrange - act - assert" standard. All test will have a similar setup, which makes them very readable and makes it more likely that other people contributing to sqlpp will follow this. 
 
Even exactly the syntax you mentioned would work, but then it's only one Test. So the SECTION Keyword (or GIVEN / WHEN / THEN thing) is really just for managing multiple Test cases. In a more traditionell Framework, you would have a fixture for this. 

```
public SomeEnvironmentACoupleOfTestsHaveInCommong {
   SomeEnvironmentACoupleOfTestsHaveInCommong() {
     // Some setup all need
   }
public: 
  Foo someDataAllNeed;
} 

TEST_F(SomeEnvironmentACoupleOfTestsHaveInCommong, "Description 1") {
   REQUIRE(to_sql_string_c(::sqlpp::context_base{}, avg(tabPerson.id) == "AVG(tab_person.id)");
   
}

TEST_F(SomeEnvironmentACoupleOfTestsHaveInCommong, "Description 2") {
   REQUIRE(to_sql_string_c(::sqlpp::context_base{}, avg(::sqlpp::distinct, tabPerson.id) == "AVG(DISTINCT tab_person.id)");
}
```

Ideally you want to have only one REQUIRE for each Test / Test Section, because you want to test one thing per test. This allows the best detection in case something is wrong. Also there is no influence on other tests. 
Imagine `to_sql_string_c` has some side effects. 
It's also not quite clear what you have identified to be tested. In my example you see it's two seperate things you test. In yours you would have to understand the code to identify if these REQUIRE belong together and test one thing or actually two. 

These are all no problems in your case. It's still only two REQUIRE and the function has no side effects. All maintainable and clean. But in my opinion it opens door for things like this: 

```
SCENARIO("Test all the code") {
   // Some Code 
   REQUIRE(...) 
   // Some Code 
   REQUIRE(...)
   // Some more Code
   REQUIRE(...)
}
```
(Saw this in production code)

So my opinion on this is: Be consistent, even if that means that simple tests feel verbose. 

But I would be fine with the other syntax, which is one intendation less. Also coming up with the descriptions for all the GIVEN, WHEN, THEN is no fun. The other side of the coin is that it doesn't enforce this "Arrange - act - asser" (-> Given When Then) Pattern. So it's a tradeoff. In my projects I use Given / When / Then, but to be honest I feel it's quite verbose too and I thought about switching to the other syntax. 
So I would perhaps go with the TEST_CASE syntax, I feel it's better suited here.

**Comment by rbock** [comment]
I think we have to distinguish between testing serialization and testing the interaction with a real database.
The former needs no preconditions (i.e. no WHEN). The latter has to be prepared, e.g. by creating tables and inserting some sample data (i.e. there clearly is a WHEN and a THEN).

For simple tests without preconditions, of the options you presented I like the TEST_CASE and SECTION variant best. I would probably use it like this.

```C++
TEST_CASE("Serialization", "Core") {
  auto serialize = [](const auto& expr) {
    return ::sqlpp::to_sql_string_c(::sqlpp::context_base{}, expr); 
  };

  SECTION("AVG") {
   REQUIRE(serialize(avg(tabPerson.id)) == "AVG(tab_person.id)");
  }

  SECTION("AVG DISTINCT") {
   REQUIRE(serialize(avg(::sqlpp::distinct, tabPerson.id)) == "AVG(DISTINCT tab_person.id)");
  }
}
```

For tests that actually require some setup (e.g. create tables in a database), I would use the `SCENARIO`, `GIVEN`, `WHEN`, `THEN` style, I guess.

**Comment by Leon0402** [comment]
> The former needs no preconditions (i.e. no WHEN)

Afaik the WHEN is always the action that needs to be taken. So in this case the when is the call of the function and the THEN is what you expect to happen. 
Although the WHEN is usually not just any call to any function, but a very specifc call. For example here it's an avg with or without distinct.

There is no GIVEN though, that would be the precondition you mentioned. 

For database test we could use the above style as well. The TEST_CASE = GIVEN, SECTION = WHEN + THEN. 

```cpp 
TEST_CASE() {
   // Here some common database setup 
   SECTION() {
       // Here test 1
   }
   SECTION() {
      // Here test 2
   }
}
```
Both sections will execute common database setup, so it's a little bit of magic :-) 

In general I think we should decide for one style and not mix them up. I now would in fact prefer the TEST_CASE / SECTION style. It's just less verbose and the GIVEN / THEN are in practice not always so splitten up. 
For example when using a Mocking Framework, you have to set the expectations (-> the THEN) before the actual function call (-> then WHEN). 
But it's your call! 

Regarding your example above: I'm slightly unsure. It is indeed quite neat and I like in that regard. I think I would also be fine in that case, the lambda is basically just an std::bind(). It's very readable and there is little chance for bugs here (-> We don't have tests for the tests, so they should be bug free :-)). 
But in general I would say we should be careful when introducing more complex code. A general rule I follow is: No ifs, no loops. That usually keeps the tests quite clean. 

I will change it to your proposed solution and write some more tests :-)

**Comment by rbock** [comment]
OK, let's go with TEST_CASE /  SECTION :-)

**Comment by Leon0402** [comment]
I used TEST_CASE as discussed. Additionally I started implementing some first tests for static assert. I also ensured that the test output would be nice in case one static assert test failed.

image

Well, not perfect I guess as the second one is wrapped, but it should be easy to see what the issue is. 


Regarding average I think I got everything covered for the test, although I could not come up with a good example for the last test case (no alias expression). Do you have one?

**Comment by rbock** [comment]
Thanks for the update! This looks really nice to me :-)

Regarding the aggregate function, I see that you are using `avg(avg(tab.id))` already. This, or `avg(count(tab.id))` would be good examples for that. Maybe that's an indicator that the order of checks should be swapped?

For the alias, you could use `avg(tab.id.as(a))`.

This is assuming `SQLPP_CREATE_NAME_TAG(a);` somewhere, not sure if you can have that inside the test case.

**Comment by Leon0402** [comment]
I'm not quite sure what I pushed yesterday, it was completly broken :-D  

Yes `avg(count(tab.id))` is obviously an example for aggregate inside aggregate. The missing test case was the one for tags. I could not declare it inside the test case, but at the top of the file. Not perfect, but okay. 

There are two more things I wonder: 
- Why is it called `NAME_TAG` and not something like alias (as in sqlpp11 I believe)? 
- How does the library handle if different things are allowed for an expression based on the database. For instance say some DBMS would allow something like `avg(someColumn as someAlias)`  and some not. Can the library handle such differences? 
Is there some SQL Standard the library currently follows? 

I would continue adding more tests for the other aggregate functions.

**Comment by Leon0402** [comment]
I added tests for max aggregate function and also added more test cases in general. 

I thought it might make sense to do some combination of whitebox and blackbox testing. Before I was concentrating on the implementation and therefore had as many test cases as there are asserts basically. 
This is somewhat error-prone, we could easily miss cases. 

For instance `max(5)` and `max(4)` are almost certainly equivalent. If one works, the other will work for sure as well, no need to test both. 
But when we have `max(Table.nonNumericColumn)` and `max(some complex subquery)` it's more difficult to tell if they are equivalent. In the current code both are ruled out by the same assert.  But still I feel I feel they are not equivalent and should both be checked to be absolutly sure. 

My suggestion is: At least have enough test cases to check the complete code (use some coverage tool to check that!), but have some additional (possibly a little bit duplicate tests), which seem to be worth it to test as well (-> Those you probably would do if you have no idea about the implementation -> Blackbox tests) 

How do you feel about the new test cases for average and max? (Maybe it's for some worth it to add more asserts to get better error messages?)

**Comment by rbock** [comment]
Re NAME vs ALIAS: I believe that name is more appropriate. It becomes an alias once it is used in `.as()`. I guess we could have a philosophical discussion about it :-)

Re Different databases allowing some things that others don't: There are examples of that already. See for instance the update clause in mysql, which accepts `order_by` and `limit`. These are special implementations in the respective database-specific include directories.

Re test cases: I think it will be tough to test all possible combinations. I would focus on orthogonal concepts. i.e. make sure that avg or max require the right combination of checks (numeric, not alias, not aggregate), and make sure that the right kind of expressions are considered to be numeric, aliases, or aggregates.

Re whitebox/blackbox testing: I won't claim I am an expert here. But my take is that we should test based on what is (should be) documented. In our example, the "concepts" in the form of static_asserts should be documented. And that is what needs to be tested.

**Comment by Leon0402** [comment]
> Re test cases: I think it will be tough to test all possible combinations. I would focus on orthogonal concepts. i.e. make sure that avg or max require the right combination of checks (numeric, not alias, not aggregate), and make sure that the right kind of expressions are considered to be numeric, aliases, or aggregates.
> 
> Re whitebox/blackbox testing: I won't claim I am an expert here. But my take is that we should test based on what is (should be) documented. In our example, the "concepts" in the form of static_asserts should be documented. And that is what needs to be tested.

So say avg(..) can expect some args and some not: 
- numeric constant (`avg(5)`) -> numeric value
- numeric column (`avg(table.someNumericColumn)`) -> numeric value
- no alias (`avg(table.numeriColumn.as(name)`) -> alias

If I do understand you right, the first two cases belong to the same `orthogonal concept`. So the question is: How can we test both.  

Your suggestion is (correct me if I didn't get it right): 
- Write a test for `has_numeric_value_v` to see that it actually identifies numeric constant as well as numeric columns
- Only test one case explicitly for avg to see if the general logic is working
- Make sure (by looking at the code) that `has_numeric_value_v`  is actually used and not some completely different method 

With the idea that we do have less tests (In the example: Only 2 for the `has_numeric_value_v` and then only one for `avg`, `sum` ... instead of 2 for each) 

I see the drawback that we rely on manual review that we actually use the correct `orthogonal concepts`. Not only now (which is not so much of a problem), but also in the future. 

We actually have a scenario for this right in the source code. The `max` function. Using the strategy to only have one tests, the following might be good test cases: 
- sqlpp::test::assert_good_expression(max(tabPerson.id));
- sqlpp::test::assert_bad_expression(sqlpp::assert_max_arg_is_not_aggregate{}, max(count(tabPerson.name)));
- sqlpp::test::assert_bad_expression(sqlpp::assert_max_arg_is_not_alias{}, max(tabPerson.id.as(tag)));

One for each assert basically. 

Now as user I'm doing `avg(42)`. I'm not sure why that would be useful, but it is valid sql :-) It currently fails whereas `avg(42)` works just right. 
So I might think: Why are they not the same? Both mathematical functions, shouldn't they accept the same input? Therefore I compare source code and do a PR with: 

`is_expression_v -> `has_numeric_value_v`

The reasoning seems good, `avg(42)` now works just fine and most importantly: All tests work! So let's ship it. 

While once could think easily `avg` and `max` take the same arguments, they don't. `max` for instance also works for character based columns! 
So we changed the behaviour of our function and no test failed :( This is clearly not ideal as one of the main reasons for tests is that it's avoids regressions. 

With the current set of tests it would fail as there is a tests to check it with character based columns. Moreover I also identified a bug with this approach, because the test case with numeric column currently don't. 

Obviously, if you do a review and think about if changing `is_expression_v` to  `has_numeric_value_v` might have some other unwanted effects (Perhaps by comparing the test cases of each to see if one has something the other don't have). 
But I believe the goal with tests is to help with the manual review as best as possible and provide good safety. 


I do think what you might worry about is the huge effort and also repetition of test cases. I don't actually think it's a lot of effort. Thinking about what SQL syntax is allowed (or looking it up in the docs :-)) is probably easier then understanding the template code.

We do have repetition though. Actually we would then also need the same tests for `avg(distinct)` by the same rationale. You should be able to change the implementation in any way and the tests should tell you if everything is still correct. 
But I do think that (this sort of) repetition is not a bad thing. The tests are simple and provide good error detection and are therefore easy to maintain I would say.
And the tests are very independent of the implementation! There is probably little need to change the tests if you change internal details. 

Note: I wouldn't say though that having as much tests as possible is desirable. For example one with `avg(1)`, one with `avg(2)` and one with `avg(3)` does not add any value. We can  almost be certain that if one works, the other works as well. 

I hope I've explained well why I think (in general) that more test cases than we have asserts are useful for a complete test suite.

**Comment by rbock** [comment]
First of all: `max(42)` should work :-)

I agree that tests should protect against accidentally narrowing or widening the interface as you described with is_expression -> has_numeric_value. That does indeed require a few more tests.

I think you are on a good path here!

**Comment by Leon0402** [comment]
> First of all: `max(42)` should work :-)

Should work right now with the current code? At least my test failed (the one I commented out for max)

> I think you are on a good path here!

Alright! Thanks for your support

**Comment by rbock** [comment]
> > First of all: `max(42)` should work :-)
> 
> Should work right now with the current code? At least my test failed (the one I commented out for max)

The code needs to be changed to allow `max(42)` or `max("forty two")`, same with other comparable value types. Haven't looked at it in detail. Do you want to give it a try?

> > I think you are on a good path here!
> 
> Alright! Thanks for your support

Sure thing. Nice to watch the progress :-)

**Comment by Leon0402** [comment]
> The code needs to be changed to allow `max(42)` or `max("forty two")`, same with other comparable value types. Haven't looked at it in detail. Do you want to give it a try?

Sure will do :-)

**Comment by Leon0402** [comment]
I did some more tests and found out that the allowed arguments for aggregate functions are different. For instance `max("Hello World")` is in some databases allowed (sqllite3, mysql) whereas in others it is not (mssql, postgresql). 

As far as I understood you, it is possible to customize the behavior for different connectors (I couldn't find the example you mentioned earlier, you got a link?). 
But what do you use by default in such a case where two databases support it and two don't? Do you use the least strict? (Therefore allow string literals in this case)

**Comment by rbock** [comment]
I am trying to determine the exception, which is not always easy (as in this case).
The core tends to be more restrictive, but not always, e.g. sqlite3 does not support outer join.

In this case, I guess I would be more restrictive, too. You can then add another max function in the `sqlpp::mysql` namespace. 

The alternative approach is to specialize the serialization with the respective context, and [prevent usage](https://github.com/rbock/sqlpp17/blob/develop/include/sqlpp17/sqlite3/default_value.h) or [change representation](https://github.com/rbock/sqlpp17/blob/develop/include/sqlpp17/mysql/clause/insert_values.h).

Note: Glancing at these serialization specializations, it seems to me that the outer join (and right outer join) are not prevented for sqlite3 yet.

**Comment by Leon0402** [comment]
I split up the tests into good and bad cases. I felt like this would be a clearer structure and less redundancy regarding the description. 

Furthermore I noted for which connectors the test hold and for which not. I have to check it anyway and thought this might be useful information to later readers of the code (to avoid confusion).

My suggestion, based on some tests, would be to allow non numeric columns and literals. I also changed the source code accordingly. 
I'm not sure if I'm completely happy with it. I fear that if more types are added this becomes `assert_max_arg_is_numeric_or_text_or_other_data_type_or_other_data_type` :-) 
I guess it would be better to say what is **not** allowed (as we do with alias, aggregate), but it's more difficult to implement. 

WDYT?

**Comment by rbock** [comment]
> I split up the tests into good and bad cases. I felt like this would be a clearer structure and less redundancy regarding the description.
Looks good to me!

> Furthermore I noted for which connectors the test hold and for which not. I have to check it anyway and thought this might be useful information to later readers of the code (to avoid confusion).

Not sure I am following? Is the idea to have additional tests with the failing connectors to prove that they are indeed failing.

> My suggestion, based on some tests, would be to allow non numeric columns and literals. I also changed the source code accordingly. I'm not sure if I'm completely happy with it. I fear that if more types are added this becomes `assert_max_arg_is_numeric_or_text_or_other_data_type_or_other_data_type` :-) I guess it would be better to say what is **not** allowed (as we do with alias, aggregate), but it's more difficult to implement.

I see that you changed `avg` to take non-numeric values, too? Personally, I would say no to that until someone shows me a compelling real-world use case.

`max` is different: max makes sense for anything that is strict weak ordering, e.g. numeric, text, date. And I guess that's what I would use for naming, see also https://en.cppreference.com/w/cpp/concepts/strict_weak_order

HTH?

**Comment by Leon0402** [comment]
> Not sure I am following? Is the idea to have additional tests with the failing connectors to prove that they are indeed failing.

My motivation was: 
- Remind me to write later specialization for the specific connectors (and tests) to deal with the connectors that behave differently than most others
- Have some documentation -> If we write later documentation for the features of sqlpp17 this could be used to write a little note in the markdown like "This feature only works for sqlite3 and mysql" or something like this. 
- Explain in a short way, why these tests are good or bad (someone with a postgresql background might be wondering: Why the hell is this syntax supposed to work, it certainly won't. With this he will see: Ah postgresql is the exception here

So "true" means: This test holds for all the connectors mentioned afterwards
And "false" means: This test does not hold for the mentioned connectors -> There is (or should be) specific handling for this in the connector

(In the best case all connectors would be "true", which basically means: This is standardized sql syntax across all connectors)

It's at least very useful to me :-) 

> I see that you changed `avg` to take non-numeric values, too? Personally, I would say no to that until someone shows me a compelling real-world use case.
> 
> `max` is different: max makes sense for anything that is strict weak ordering, e.g. numeric, text, date. And I guess that's what I would use for naming, see also https://en.cppreference.com/w/cpp/concepts/strict_weak_order

Yes I fully agree! It doesn't make a lot of sense to me either to allow text values here. 

My rationale here was to stick to what the connectors allow. In this case the majority (sqlite3 and mysql) of the connectors allow a text data type. 
But I think it might be better to stick to what is logical and therefore remove the added code for `avg`. 

Would you therefore also not write specific code for that connector to allow it in the case of sqlite3 / mysql?  I don't have a strong opinion here. I think this is more a general design decision (whether you want to disallow or discourage things that make no sense or where there are better alternatives).

Regarding the real world use case: 
I think this feature exists, because in sqlite3 it is possible to have columns with mixed data types. Therefore non numeric stuff is interpreted as zero. (See: https://www.sqlitetutorial.net/sqlite-avg/). 
But I don't think this a valid use case for sqlpp as we cannot have mixed data types in one column.

**Comment by rbock** [comment]
Thanks for clarification regarding the notation. Let's move ahead and see where this takes us.

Regarding average: I would not write specific code for connectors that allow text (again, unless someone presents a compelling reason). And as you said, mixed data types in a column would probably look rather strange in sqlpp. A variant type, maybe? I probably would not go there.

**Comment by Leon0402** [comment]
> A variant type, maybe? I probably would not go there.

I agree! 

- Fixed avg as discussed (two commits, I fucked up the first time :-)) 
- Use notation of orderable for max 
- Added min which is the same as max 
- Added sum which is the same as avg 

Next would be `count`, which is quite different to the others I think. 

valid (and useful): 
- `COUNT(some_colum)` 
- `COUNT(*)`
- `COUNT(DISTINCT some_column [, someMoreColum])` 

also valid (probably not very useful): 
- `COUNT(literal_value)` -> Use `COUNT(*)` instead 
- Weird calculations like `COUNT(some_column + some_column)` 

Did I forget anything? 

Based on the identified test cases I think checks like these would be useful: 
- Check if it's a column of any type or sqlpp::all (this is * right?) 
- Check it's not an alias as usual
- Possibly a check for aggregate in aggregate as usual? (Not sure as this is probably filtered by the first condition already and I don't think it needs an extra explanation)

Use some variadic template magic for distinct with the same check except sqlpp::all (`COUNT(DISTINCT *)` is not valid)

We could also make `count()` be `COUNT(*)`. This is not as close to the sql syntax, but nice to read and more logical in my opinion that `count(sqlpp::all)`. WDYT?

**Comment by rbock** [comment]
Btw, I would suggest to merge the current status some time soon. I think it is great progress and it would be a shame if it got lost through some f***-up :-)

`sqlpp::all` is a flag like sqlpp::distinct. It can be used in `union` for instance. We _could_ use it in count to express `*`, but it would break semantics.

afaict, `count(1)` does the same as `count(*)`, so I would use that or `count(tab.id)`, assuming that `id` is a unique column.

We could also create a new entity to symbolize the asterisk, like `star` or `asterisk`. Or we could try to get really close to `*` and have a dereferenceable entity called `_`. To be used as 

 - `count(sqlpp::star)`
 - `count(sqlpp::asterisk)`
 - `count(sqlpp::*_)`

With a` using` declaration this could be turned into

 - `count(star)`
 - `count(asterisk)`
 - `count(*_)`

The first would be my favorite, if we want to introduce something to represent the `*` symbol. Of course, once we had, say, `count(star)`, people would ask for `select(star)`. That's certainly possible, but pretty difficult, afaict. That's why there is `all_of`.

Or, of course, have a separate function called `count_star()`.

Hard to say. Maybe implementing `select(star)` would be worth it?

**Comment by Leon0402** [comment]
I agree, merging soon sounds good to me. 

Ahh I confused `sqlpp::all` with `all_of`. We shouldn't use it for that purpose then :-) 

Yes `count(1)` should do the same (any other number as well). I don't like it too much, but we probably should support it as many people use it. 

My favorite would be `count(star)` as well, so let's go with that :-)  `select(star)` is definitely needed, but this is something for another PR :D  

> Or, of course, have a separate function called `count_star()`.

I  would then rather prefer just a simple `count()` or `select()` I guess.

**Comment by rbock** [comment]
OK, cool, then let's go for `count(star)` and `select(star)` :-)

**Comment by Leon0402** [comment]
Sorry, took me some time to continue working on this. I migrated the PR to Catch3, which is the current release. Furthermore, I added the count tests and implemented `sqlpp::star`. 

I probably didn't implement  `sqlpp::star` in the best way. I wasn't quite sure if it is considered an expression for instance. Can you have a look? 

Other than that, this PR is ready to be merged from my side. And I will continue work in another MRs.

**Comment by rbock** [comment]
Nice work.
`sqlpp::star`should not be an expression. I think it is good as it is.

**Comment by rbock** [comment]
I like the `count(sqlpp::star)` :-)

**Comment by Leon0402** [comment]
> Nice work. `sqlpp::star`should not be an expression. I think it is good as it is.

But I think, it is right now. I gave it a value type, so `ìs_epression_v` will be `True for `sqlpp::star`.

**Comment by rbock** [comment]
Ooops, right!
It might be better to have an explicit overload for creating `count` with `star`. Otherwise, if there ever were another function that can take just any expression, it would also accept `star` which might not be what we want...

**Pull request merged**
